### ISSUE TITLE
[MongoDb] update document must contain key beginning with '$'

### ISSUE THREAD

**Issue by TamNguyenMinh2494** [AmbroseNTK/HealthyEatingCore#2]
Passed user's id and value in picture below, but it shows error!!! 

![image](https://user-images.githubusercontent.com/41353457/107121817-0533e600-68c7-11eb-887c-088abee573e7.png)

**Comment by AmbroseNTK** [comment]
Which error???

**Comment by AmbroseNTK** [comment]
Okay, I got it!
We should use BSON for CRUD operating instead of using map[string]interface{}. That is require of MongoDB Driver for Golang
